[package]
name = "spotify-tools"
version = "0.1.0"
authors = ["tmkch <tomekch6@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
open = "1.3.2"
url = "2.1.0"
dialoguer = "0.4.0"
